import React from "react";
import { Link } from "react-router-dom";
import { Shield, ArrowLeft } from "lucide-react";
import SiteFooter from "@/components/layout/SiteFooter";

export default function PrivacyPolicy() {
  return (
    <div className="min-h-screen bg-background">
      <div className="max-w-3xl mx-auto px-6 py-12">
        <Link to="/" className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground mb-8 transition-colors">
          <ArrowLeft className="w-4 h-4" /> Back to Home
        </Link>
        <div className="flex items-center gap-3 mb-8">
          <div className="w-10 h-10 rounded-xl bg-primary/10 flex items-center justify-center">
            <Shield className="w-5 h-5 text-primary" />
          </div>
          <div>
            <h1 className="text-2xl font-display font-bold text-foreground">Privacy Policy</h1>
            <p className="text-xs text-muted-foreground mt-0.5">Last updated: June 2026</p>
          </div>
        </div>

        <div className="space-y-6 text-sm text-muted-foreground leading-relaxed">
          <section className="space-y-3">
            <h2 className="text-base font-semibold text-foreground">1. Information We Collect</h2>
            <p>We collect information you provide directly (name, email, phone), information generated by your use of the Platform (transaction history, listings, bids), and technical data (IP address, browser type, cookies).</p>
          </section>
          <section className="space-y-3">
            <h2 className="text-base font-semibold text-foreground">2. How We Use Your Information</h2>
            <p>We use your data to operate the Platform, process transactions, send notifications, improve our services, comply with legal obligations, and prevent fraud.</p>
          </section>
          <section className="space-y-3">
            <h2 className="text-base font-semibold text-foreground">3. Data Sharing</h2>
            <p>We share your data with counterparties in transactions you initiate, payment processors (Stripe), and service providers under confidentiality agreements. We do not sell your personal data.</p>
          </section>
          <section className="space-y-3">
            <h2 className="text-base font-semibold text-foreground">4. Data Security</h2>
            <p>We implement industry-standard security measures including encryption, access controls, and regular security audits. However, no system is 100% secure.</p>
          </section>
          <section className="space-y-3">
            <h2 className="text-base font-semibold text-foreground">5. Cookies</h2>
            <p>We use cookies and similar technologies for authentication, preferences, and analytics. You can control cookie settings in your browser.</p>
          </section>
          <section className="space-y-3">
            <h2 className="text-base font-semibold text-foreground">6. Your Rights</h2>
            <p>You have the right to access, correct, or delete your personal data. To exercise these rights, contact us through our <Link to="/contact" className="text-primary hover:underline">contact page</Link>.</p>
          </section>
          <section className="space-y-3">
            <h2 className="text-base font-semibold text-foreground">7. Retention</h2>
            <p>We retain your data as long as your account is active or as needed to provide services, comply with legal obligations, resolve disputes, and enforce agreements.</p>
          </section>
          <section className="space-y-3">
            <h2 className="text-base font-semibold text-foreground">8. Changes</h2>
            <p>We may update this policy periodically. We'll notify you of material changes via email or in-app notification.</p>
          </section>
        </div>
      </div>
      <SiteFooter />
    </div>
  );
}